language: java
jdk:
  - oraclejdk8

dist: trusty
sudo: false

cache:
  directories:
  - $HOME/protobuf
  - $HOME/.m2

before_install:
  - bash tools/install-protobuf.sh
  - export PATH=$HOME/protobuf/bin:$PATH
